dist: trusty
sudo: required
language: python
python:
  - "3.5"
#  - "nightly"
# env:
#  - DJANGO_VERSION=1.6
#  - DJANGO_VERSION=1.7
#  - DJANGO_VERSION=1.8
#  - DJANGO_VERSION=1.10

#addons:
#  apt_packages:
#     - swig
#     - libssl-dev
#     - libssl0.9.8
#     - libcups2-dev
#     - unixodbc-dev
#     - python-mysqldb

services:
  - mysql

before_install:
    - "export DISPLAY=:99.0"                         
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

virtualenv:
  system_site_packages: true

install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install flake8
  - pip install coveralls

before_script:
  - flake8 edc_base
  - mysql -e 'create database edc;'
  # - mysql -e 'create database edc_lab;'

script: 
  - coverage run --source=edc_base manage.py test

after_success:
  - coveralls
